.eslintrc.json
package-lock.json
package.json

안쓰는 import 구문 정리하는 eslint를 추가하였습니다.

[13] feat: 안쓰는 import 구문 정리하는 eslint

---

.eslintrc.json

- 기존 : 안쓰는 변수 에러로 화면이 로드가 안됌
- 변경 : 안쓰는 변수는 경고처리로 밑줄만 나타나도록 설정함

[13] feat : 안쓰는 변수의 경우 에러처리에서 경고처리로 변경

---

.prettierrc.json
package-lock.json
package.json

- tailwind를 프리티어로 규칙성있게 자동정렬 시켜주는 플러그인 설치

[13] feat: tailwind 프리티어 추가

---

src/components/Navbar.tsx
src/page/Home.tsx

- 여행지 입력후 나타나는 여행지 목록 리스트 부분 UI 작업
- 활성화/ 비활성화 되는 부분에 active로 분기처리하여 작업하였습니다. 추후에 작업하시는 분이 active 부분에 조건 설정하시고 사용하시면 될것 같습니다 !!!! ( 임시데이터 )
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[37] feat : 여행지 추가 후 여행지 목록 리스트 UI 레이아웃

---

src/components/FlightPlansSection/FlightList.tsx
src/components/FlightPlansSection/FlightPlans.tsx
src/index.css
tailwind.config.js

비행기 UI 구현했습니다.
아직 데이터가 없어서 대충 데이터 값을 넣는다고 가정하고 진행했고
경유지 추가되는 부분은 주석으로 적어두었습니다. 데이터 유무에 따라 조건 분기 처리하면 될것 같습니다.
추후 클릭시 사이드바에서 나오는 창으로 생각했을때 그대로 높이값만 주면 모양은 유지됩니다 !
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[41] feat: 비행기 UI 구현

---

src/App.tsx
src/components/AccommodationSection/Accommodation.tsx
src/components/ActivitySection/Activity.tsx
src/components/Body.tsx
src/components/Weather/WeatherList.tsx
src/context/TabContext.tsx
src/page/Home.tsx

더보기 버튼 클릭시 -> 예약탭 이동하도록 수정하였습니다 !

[44] feat: tab 상태값 context로 생성 후, 변경, 더보기 클릭시 탭 이동하도록 수정

---

src/components/Header.tsx
src/components/Navbar.tsx
src/indexeddb/indexedDB.ts
src/page/Home.tsx

home 컴포넌트에서 indexedDB를 조회하여 
1 객체 리스트와 선택한 idx를 관리하는 useState를 Nav 컴포넌트에 넘겨줍니다.
2 선택한 idx를 Header 컴포넌트에 넘겨줍니다.
Nav 컴포넌트에서는 전달받은 리스트를 배열의 Map 메서드로 순회하여 리스트아이템을 만듭니다.
Header 컴포넌트는 전달받은 idx로 indexedDB를 조회합니다.
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[48]feat:선택한 id로 indexedDB 데이터 조회

---

package-lock.json
package.json
src/components/AddTravelDestination.tsx
src/components/Navbar.tsx
src/components/common/Modal.tsx
src/context/ModalContext.tsx
src/context/selectBox/SelectInput.tsx
src/indexeddb/indexedDB.ts
src/page/Home.tsx
src/provider/AddTravelDestinationProvider.tsx

- [34] feat: 여행지 추가 기능 작업
- 여행지 추가 UI 작업
- 모달 context 수정
footer에 버튼은 각각의 form 에서 다루는걸로 하여서 뺐습니다.
- 여행지 IndexdedDB 로 추가
<br/>
<br/>
- [여행지 추가 기능 작업 #34 ](https://github.com/FE-MWM/WanderGuide/issues/34)
<br/>

[34] feat: 여행지 추가 기능 작업

---

.eslintrc.json
package-lock.json
package.json
src/App.tsx
src/components/AddTravelDestination.tsx
src/components/FlightPlansSection/FlightList.tsx
src/index.tsx
src/indexeddb/indexedDB.ts
src/page/Home.tsx
src/provider/AddTravelDestinationProvider.tsx
src/store/destinationAtoms.tsx

- [57] feat: recoil 셋팅 및 테스트
- recoil 기본 셋팅
- 여행지 추가시 리스트에 바로 보여지는지 테스트
<br/>
- recoil 셋팅 후 eslint 부분 설정할때 아래를 추가하면 react Hook useEffect has a missing dependency: 'setPlanList'. Either include it or remove the dependency array. 에러가 발생합니다.
경고는 setPlanList 함수가 useEffect 내에서 사용되었지만 의존성 배열에 포함되지 않았다는 것을 알려주고 있는 에러인데
react-hooks/exhaustive-deps 를 off 로 하거나 // eslint-disable-next-line react-hooks/exhaustive-deps 주석을 추가하라고 나와있는데 어떤걸 선택하는게 나을까요? 
주석을 하게되면 반복적으로 주석을 달아야하고 off 를 하면 규칙을 무시하게 되니 가능한 사용하지 않는것이 좋다고 합니다.
(참고 home.tsx 파일)
.eslintrc.json
```
{
"plugins": ["react-hooks"],
"rules": {
"react-hooks/rules-of-hooks": "error",
"react-hooks/exhaustive-deps": [
"warn",
{
"additionalHooks": "useRecoilCallback"
}
]
}
}
```
home.tsx
```
useEffect(() => {
initDB();
getStoreData().then((res) => { …
```

[57] feat : recoil 셋팅 및 테스트

---

public/images/close.svg
src/App.tsx
src/components/FlightPlansSection/FlightList.tsx
src/components/FlightPlansSection/FlightPlans.tsx
src/components/common/Modal.tsx
src/components/common/SideModal.tsx
src/context/SideModalContext.tsx
src/page/Home.tsx
tailwind.config.js

- 사이드 모달창 공통 컴포넌트 구현 !! 
- fullsIze 옵션을 두어서 fullSize props로 받으면 풀 사이즈 크기의 모달창이 나오도록 했습니다. ( 옵션값)
- 비행기 대쉬보드에서 클릭하면 -> 사이드모달창 켜지도록 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[43] feat : 사이드 모달 창 구현 

---

src/components/Header.tsx

indexedDB 삭제 후 
데이터가 없는 경우에도 헤더 보이게 수정하였습니다
<br/>

[48]fix: indexedDB에 데이터 없는 경우 <Header /> 아예 안보이는 문제 수정

---

src/context/selectBox/SelectInput.tsx
src/hook/useCountries.ts

-  input에 값이 없으면 리스트를 접을 수 있습니다!
- 기존의 나라를 선택하면 수정안되는 기능을 수정되도록 변경하였습니다.
- input 입력값이 없으면 모든 나라 리스트를 보여주는 거 수정하였습니다. 
<br/>

[46] feature: 나라 선택 셀렉트박스의 리스트 접기/펴기 기능, 입력값 수정 기능 업그레이드

---

src/components/FlightPlansSection/AddFlight.tsx
src/components/FlightPlansSection/AddFlightItem.tsx
src/components/FlightPlansSection/FlightPlans.tsx
src/components/common/Modal.tsx
src/components/common/SideModal.tsx
src/context/SideModalContext.tsx
src/indexeddb/indexedDB.ts
src/provider/AddFlightPlanProvider.tsx

미완성 부분이라 추후 다시 pr 날리겠습니다 
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[56] feat: 비행기모달 -1차 

---

src/components/AccommodationSection/Accommodation.tsx
src/components/AccommodationSection/AddAccommodation.tsx
src/provider/AddAccommodationProvider.tsx

모달창 UI 구현 
기능구현은 상태관리 후 진행하겠습니다. 
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
리액트 모달 훅폼으로 데이터 저장하기
<br/>
<br/>

[63]feat : 숙소 모달창 구현 

---

src/components/FlightPlansSection/FlightPlans.tsx

환율영역이 들어가면서 깨진 비행기 영역 높이값 수정하였습니다. 
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[72] fix : 비행기 ui 깨짐 오류 수정

---

src/components/Header.tsx
src/components/Navbar.tsx
src/components/TravelItinerarySection/TravelItinerary.tsx
src/indexeddb/indexedDB.ts
src/page/Home.tsx
src/provider/AddTravelDestinationProvider.tsx
src/store/destinationAtom.ts
src/store/destinationAtoms.tsx
src/store/planListAtom.ts

- [57] feat: recoil 데이터 구조 설계
- recoil & IndexedDB 데이터 구조 설계
- 여행지 추가시 실시간 동기화 작업
<br/>
- [데이터 구조 설계#57](https://github.com/FE-MWM/WanderGuide/issues/57)
<br/>

[57] feat: recoil & IndexedDB 데이터 구조 설계

---

src/components/TravelItinerarySection/TravelItinerary.tsx

fix: planInfo 오류 수정

---

src/components/ActivitySection/Activity.tsx
src/components/ActivitySection/ActivityModal.tsx

- 모달의 input과 textarea에 값을 입력하고 확인을 누르면 폼데이터로 연결이 됩니다!
<br/>
<br/>
둘다 필수값으로 설정해놔야겠죠?
입력이 안되었을 경우 확인 버튼을 비활성화 시킬지, 알림 모달을 띄우는게 좋을지 고민입니다
- #66 
<br/>

[66] feat: 액티비티 모달 폼 기능 추가

---

src/page/Home.tsx

fix: indexedDB 데이터 없을때 빈 배열로 저장되는 이슈 수정

fix: indexedDB 데이터 없을때 빈 배열로 저장되는 이슈 수정

---

src/components/AccommodationSection/Accommodation.tsx
src/components/ActivitySection/Activity.tsx
src/components/AddTravelDestination.tsx
src/components/Header.tsx
src/components/Navbar.tsx
src/components/TravelItinerarySection/TravelItinerary.tsx
src/components/Weather/Weather.tsx
src/provider/AddTravelDestinationProvider.tsx
src/store/destinationAtom.ts

데이터가 없을 경우의 수를 넣었습니다 ! 
아직 데이터 값은 가짜 데이터로 들어가있습니다
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[76] feat :  데이터가 없는 경우 경우의 수 추가 

---

src/provider/AddTravelDestinationProvider.tsx

fix: D-day영역 데이터 동기화 안되는 부분 수정

---

src/components/Weather/WeatherList.tsx
src/store/destinationAtom.ts

날씨 데이터 받아오는 부분 리코일 사용하였습니다. 
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[80] feat : 날씨 데이터 api 수정 

---

src/Util/calcCash.ts
src/components/CountriesSelectBox.tsx
src/components/ExchangeRateSection/ExchangeRate.tsx
src/components/MainDashboard.tsx
src/context/selectBox/SelectInput.tsx
src/hook/useCountries.ts
src/hook/useGetExchangeRate.ts

- recoil 을 이용해 사용자가 선택한 여행지 나라이름으로 환율을 구합니다.
<br/>
<br/>
- #77 
<br/>

[77] feat: recoil로 여행지 읽어서 환율 계산

---

package-lock.json
package.json
src/api/country.ts
src/components/CountriesSelectBox.tsx
src/components/CurrentTimeSection/CurrentTime.tsx
src/hook/useCountries.ts
src/provider/AddTravelDestinationProvider.tsx
src/store/destinationAtom.ts
src/store/initAtom.ts

- [55] feat: 현재 시각 부분 UI & 기능 구현
- 현재 시각 부분 UI & 기능 구현
<br/>
<br/>
- [현재 시각 부분 UI & 기능 구현 #55 ](https://github.com/FE-MWM/WanderGuide/issues/55)
<br/>

[55] feat: 현재 시각 부분 UI & 기능 구현

---

src/components/CountriesSelectBox.tsx
src/hook/useCountries.ts

fix: 에러 수정

---

src/Util/calcDate.ts
src/Util/calcExchangeDate.ts
src/api/exchange.ts
src/components/AccommodationSection/Accommodation.tsx
src/components/BookingSection/AccoBookItem.tsx
src/components/BookingSection/AccommodationList.tsx
src/provider/AddAccommodationProvider.tsx

- recoil을 이용해 숙소 데이터를 가져와 UI 컴포넌트를 보여줍니다.
- 기존의 <BookItem /> 컴포넌트를 복사하여 새 숙소용 UI 컴포넌트를 만들었습니다.
- daysjs 를 이용하여 숙소의 날짜 정보를 UI 컴포넌트에 맞게 가공해주는 함수를 만들었습니다.
<br/>
<br/>
-  const getDiff = (item: { startDate: string; endDate: string }) => { ...
파라미터를 객체로 받으면 파라미터의 값을 키로 명시해서 받을 수 있다는 점이 좋아서 
이렇게 해보았는데요.. 단점은 키도 같이 입력해야해서 타이핑이 번거롭고, 글자가 많아보입니다..
함수 파라미터 타입은 어떤 방식을 더 선호하시나요?
<br/>
- #89
<br/>

[89] feat: 예약 탭의 숙소 정보 UI 와 숙소 정보 연결

---

src/components/CurrentTimeSection/CurrentTime.tsx
src/components/TravelItinerarySection/TravelItinerary.tsx

- [54] fix: D-day 구현 및 현재 시각 부분 수정
- D-day 구현
- 현재 시각 부분 수정
<br/>
<br/>
- [#54]
<br/>

[54] fix: body 영역에 D-day 구현 및 현재 시각 부분 수정

---

src/Util/calcDate.ts
src/Util/calcExchangeDate.ts
src/api/exchange.ts
src/components/AccommodationSection/Accommodation.tsx
src/components/BookingSection/AccoBookItem.tsx
src/components/BookingSection/AccommodationList.tsx
src/indexeddb/indexedDB.ts
src/provider/AddAccommodationProvider.tsx
src/provider/AddTravelDestinationProvider.tsx

- 숙소 정보 추가 모달을 '수정' 할 때도 사용할 수 있도록 분기 처리 하였습니다
- 숙소 정보 수정 기능 추가
- 추가, 수정 함수 부분이 좀 억지스러운 느낌이 드는 거 같아서 고민입니다.... 
더 간결하고 명확하게 고칠 수 있을 거 같은데... 현재로썬 잘 모르겠습니다.
- #88 
<br/>

[88] feat: 숙소 정보 CRUD

---

src/Util/calcDate.ts
src/Util/calcExchangeDate.ts
src/api/exchange.ts
src/components/AccommodationSection/Accommodation.tsx
src/components/BookingSection/AccoBookItem.tsx
src/components/BookingSection/AccommodationList.tsx
src/indexeddb/indexedDB.ts
src/provider/AddAccommodationProvider.tsx
src/provider/AddTravelDestinationProvider.tsx

- addData 함수의 리턴값으로 indexedDB에 새로 추가된 데이터의 id 값을 보내도록 수정하였습니다.
<br/>
<br/>
- #96 
<br/>

[96] fix : 여행지 추가 시 indexedDB의 id값 얻기

---

src/api/exchange.ts
src/components/BookingSection/AccommodationList.tsx
src/components/FlightPlansSection/FlightList.tsx
src/indexeddb/indexedDB.ts
src/provider/AddTravelDestinationProvider.tsx

- [99] feat: 제목
- 처음 여행지 등록시 recoil에 id 못찾는 오류 수정
- 불필요 console.log 삭제
<br/>
- [#99 ]
<br/>

[99] fix: 처음 여행지 등록시 recoil에 id 못찾는 오류 수정

---

src/api/exchange.ts

- 크롬 익스텐션에서 api 주소를 허용하는 설정을 추가하였습니다!
<br/>
- #105 
<br/>

[105] fix: 크롬 익스텐션 환율 api cors 해결

---

src/components/AccommodationSection/Accommodation.tsx
src/components/ActivitySection/Activity.tsx
src/components/AddTravelDestination.tsx
src/components/BookingSection/AccoBookItem.tsx
src/components/BookingSection/AccommodationList.tsx
src/components/BookingSection/ActivityItem.tsx
src/components/BookingSection/ActivityList.tsx
src/components/CurrentTimeSection/CurrentTime.tsx
src/components/FlightPlansSection/FlightPlans.tsx
src/components/TravelItinerarySection/TravelItinerary.tsx
src/components/common/Modal.tsx
src/context/selectBox/SelectList.tsx
src/context/selectBox/SlectItem.tsx

- 숙소, 액티비티 예약에서 데이터 없을 경우 기본 UI 추가
- 첫 셋팅시 비행일정, 숙소, 액티비티/투어도 아예 선택 불가하도록 수정함 
- 숙소, 액티비티 삭제 버튼 위치 추가 및 높이값 수정
- 여행지 추가시 input 박스 디자인 수정 
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>
<br/>

[101] feat : 숙소, 액티비티 UI 수정, 기능 수정  

---

src/Util/dateFormatter.ts
src/components/CurrentTimeSection/CurrentTime.tsx
src/components/ExchangeRateSection/ExchangeRate.tsx
src/hook/useGetExchangeRate.ts

- 환율 로딩 스피너 추가
- dayjs 관련 유틸함수 분리 
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[111] feat: 환율, 시간 로딩 스피너 추가 및  유틸함수분리

---

src/components/Navbar.tsx
src/indexeddb/indexedDB.ts
src/provider/AddTravelDestinationProvider.tsx

- [114] feat: 여행지 삭제 기능 구현
- 여행지 삭제 기능 구현
<br/>
- [#114 ]
<br/>

[114] feat: 여행지 삭제 기능 구현

---

public/background.js

- background.js 의 새 창 사이즈 조절
<br/>
- #124 
<br/>

[124] style: 크롬 확장 프로그램 새 창 사이즈 조절

---

package-lock.json
package.json
src/components/AddTravelDestination.tsx

- 기존 input type='date'를 antd 라이브러리의 달력으로 교체하였습니다
- 여행 시작날보다 여행 마지막날이 큰 경우, 선택한 마지막날을 시작날로 자동 변경되도록 구현하였습니다
<br/>
<br/>
=>  antd 라이브러리의 달력 이미지 입니다..!
<br/>
-  antd 라이브러리의 달력  디자인이 심플해서 괜찮지않을까 싶은데 어떠신가요?!
디자인 커스텀이 세세하게 변경할 수는 없어서, 다른 디자인을 원하신다면 달력 컴포넌트를 자체적으로 만들어야 할 거 같습니다...!!!
<br/>
- [#134]
<br/>

[134] feat: 여행 날짜 유효성검사 추가 & antd 라이브러리 달력으로 교체

---

public/images/info-circle.svg
src/components/AccommodationSection/AddAccommodation.tsx
src/components/ActivitySection/ActivityModal.tsx
src/components/BookingSection/AccommodationList.tsx
src/components/BookingSection/ActivityItem.tsx
src/components/common/ConfirmModal.tsx

- [115][133] fix: 저장, 삭제 모달창 추가
1. 모달 info 아이콘 추가
2. 숙소, 액티비티/투어 저장, 삭제 모달창 추가
<br/>
- [레포 이름 #115 ]
<br/>

fix: 저장, 삭제 모달창 추가
